"use client";

import { useRef } from "react";
import type { RemoteCameraHostController } from "../hooks/use-remote-camera-host";
import { shouldKeepRemoteCameraOnDismiss } from "../lib/remote-camera";
import styles from "./booth-session.module.css";

interface RemoteCameraPairingProps {
  pairing: RemoteCameraHostController;
  disabled: boolean;
  onStart: () => void;
}

export function RemoteCameraPairing({
  pairing,
  disabled,
  onStart,
}: RemoteCameraPairingProps) {
  const dialogRef = useRef<HTMLDialogElement>(null);

  function openDialog() {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (!dialog.open) dialog.showModal();
    if (pairing.state === "idle" || pairing.state === "error") {
      onStart();
    }
  }

  function dismissDialog() {
    if (!shouldKeepRemoteCameraOnDismiss(pairing.state)) pairing.stop();
    dialogRef.current?.close();
  }

  function endConnection() {
    pairing.stop();
    dialogRef.current?.close();
  }

  const status =
    pairing.state === "starting"
      ? "Menyiapkan QR dan koneksi…"
      : pairing.state === "waiting"
        ? "Pindai QR dari ponsel. Sesi berlaku 5 menit."
        : pairing.state === "connecting"
          ? "Ponsel ditemukan. Menyambungkan kamera…"
          : pairing.state === "connected"
            ? "Kamera ponsel terhubung ke pratinjau booth."
            : pairing.state === "error"
              ? "Pairing belum berhasil. Coba lagi atau gunakan kamera komputer."
              : "Pindai QR menggunakan kamera ponsel untuk memulai.";

  return (
    <>
      <button
        className={styles.remoteCameraButton}
        type="button"
        onClick={openDialog}
        disabled={disabled}
      >
        {pairing.state === "connected"
          ? "Kamera HP terhubung"
          : "Gunakan kamera HP"}
      </button>
      <dialog
        ref={dialogRef}
        className={styles.remoteCameraDialog}
        aria-labelledby="remote-pairing-title"
        onCancel={(event) => {
          event.preventDefault();
          dismissDialog();
        }}
        onClick={(event) => {
          if (event.target === dialogRef.current) dismissDialog();
        }}
      >
        <div className={styles.remoteCameraDialogHeader}>
          <div>
            <p className={styles.eyebrow}>Pairing privat</p>
            <h2 id="remote-pairing-title">Gunakan Kamera HP</h2>
          </div>
          <button
            className={styles.remoteCameraClose}
            type="button"
            aria-label="Tutup dialog kamera HP"
            onClick={dismissDialog}
          >
            ×
          </button>
        </div>
        <p className={styles.remoteCameraInstructions}>
          Buka kamera ponsel, pindai QR ini, lalu izinkan akses kamera. Kedua
          perangkat harus bisa membuka alamat HTTPS booth yang sama.
        </p>
        {pairing.qrCodeUrl ? (
          // The QR is generated by the API from the exact phone URL.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            className={styles.remoteCameraQr}
            src={pairing.qrCodeUrl}
            alt="Kode QR untuk menyambungkan kamera ponsel ke booth"
          />
        ) : pairing.state === "starting" ? (
          <div className={styles.remoteCameraQrPlaceholder} role="status">
            Menyiapkan kode QR…
          </div>
        ) : null}
        {pairing.phoneUrl ? (
          <a className={styles.remoteCameraPhoneLink} href={pairing.phoneUrl}>
            Buka halaman kamera ponsel
          </a>
        ) : null}
        <p
          className={styles.remoteCameraStatus}
          role="status"
          aria-live="polite"
        >
          {status}
        </p>
        {pairing.error ? (
          <p className={styles.remoteCameraError} role="alert">
            {pairing.error}
          </p>
        ) : null}
        <p className={styles.remoteCameraPrivacy}>
          Video dikirim langsung antarperangkat lewat WebRTC. Server hanya
          menyimpan data pairing sementara; foto tetap diproses di browser.
        </p>
        <div className={styles.remoteCameraActions}>
          {pairing.state === "error" ? (
            <button
              className={styles.primaryButton}
              type="button"
              onClick={onStart}
            >
              Buat QR baru
            </button>
          ) : null}
          {pairing.state === "connected" ? (
            <>
              <button
                className={styles.secondaryButton}
                type="button"
                onClick={dismissDialog}
              >
                Lanjut ke booth
              </button>
              <button
                className={styles.secondaryButton}
                type="button"
                onClick={endConnection}
              >
                Akhiri koneksi
              </button>
            </>
          ) : (
            <button
              className={styles.secondaryButton}
              type="button"
              onClick={dismissDialog}
            >
              Tutup
            </button>
          )}
        </div>
      </dialog>
    </>
  );
}
